name: 'check-docker-security'
description: 'Install docker security commands.'
inputs:
  file:
    description: 'Specify the path to the Dockerfile.'
    required: true
    default: 'Dockerfile'
  image:
    description: 'Specify the image name.'
    required: true
  tag:
    description: 'Specify the tag name.'
    required: true
    default: latest
  username:
    description: 'Specify the username for ghcr.io.'
    required: true
    default: ${{ github.repository_owner }}
  password:
    description: 'Specify the password for ghcr.io.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        file: ${{ inputs.file }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.file }}:${{ inputs.tag }}
