name: Publish Docker image for Terrform AWS
on:
  push:
    branches:
      - "master"
    # paths:
    #   - "docker/base/aws/Dockerfile"
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          file: docker/base/aws/Dockerfile
          repository: ${{ github.repository_owner }}/terraform-aws
          tag_with_ref: true
