# https://docs.github.com/ja/packages/working-with-a-github-packages-registry/working-with-the-container-registry
name: Publish Docker image for Terrform GCP
on:
  push:
    branches:
      - "master"
    paths:
      - "docker/base/gcp/Dockerfile"
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          file: docker/base/gcp/Dockerfile
          repository: ${{ github.repository_owner }}/terraform-gcp
          tag_with_ref: true
